service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  deploymentMethod: direct

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
