service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::295392528210:role/lambda-dynamo-apigateway-role

plugins:
  - serverless-webpack

package: 
  individually: true

functions:
  getMenu: 
    handler: functions/getMenu.getMenu
    events:
      - httpApi:
          path: /menu
          method: GET
  createMenu:
    handler: functions/createMenu.createMenu
    events: 
      - httpApi:
          path: /menu
          method: POST
  getOrders:
    handler: functions/getOrders.getOrders
    events:
      - httpApi:
          path: /orders
          method: GET
  createOrder:
    handler: functions/createOrder.createOrder
    events:
      - httpApi:
          path: /order
          method: POST
  getOrdersByUserId:
    handler: functions/getOrdersByUserId.getOrdersByUserId
    events:
      - httpApi:
          path: /user/orders
          method: GET

resources:
  Resources:
    menuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: menuTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: orderTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST