service: backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::295392528210:role/lambda-dynamo-apigateway-role

plugins:
  - serverless-webpack

package: 
  individually: true

functions:
  getMenu: 
    handler: functions/getMenu.getMenu
    events:
      - httpApi:
          path: /menu
          method: GET
  createMenu:
    handler: functions/createMenu.createMenu
    events: 
      - httpApi:
          path: /menu
          method: POST
  updateMenu:
    handler: functions/updateMenu.updateMenu
    events:
      - httpApi:
          path: /menu
          method: PUT
  getOrders:
    handler: functions/getOrders.getOrders
    events:
      - httpApi:
          path: /orders
          method: GET
  createOrder:
    handler: functions/createOrder.createOrder
    events:
      - httpApi:
          path: /order
          method: POST
  updateOrder:
    handler: functions/updateOrder.updateOrder
    events:
      - httpApi:
          path: /order
          method: PUT
  getOrderById:
    handler: functions/getOrderById.getOrderById
    events:
      - httpApi:
          path: /order/{id}
          method: GET
  getOrdersByUserId:
    handler: functions/getOrdersByUserId.getOrdersByUserId
    events:
      - httpApi:
          path: /user/orders
          method: POST
  getUser:
    handler: functions/getUser.getUser
    events:
      - httpApi:
          path: /user
          method: POST
  createUser:
    handler: functions/createUser.createUser
    events:
      - httpApi:
          path: /user/create
          method: POST

resources:
  Resources:
    menuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: menuTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    orderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: orderTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-gsi
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

